services:
  hometube:
    image: ghcr.io/egalitarianmonkey/hometube:latest
    # build: .
    container_name: hometube
    env_file: .env
    environment:
      - TZ=${TZ:-Europe/Paris}
    ports:
      - "${PORT:-8510}:8501"
    # chemins "génériques" — valeurs par défaut utiles en dev
    volumes:
      - "${VIDEOS_FOLDER_DOCKER_HOST:-./downloads}:/data/Videos"
      - "${TMP_DOWNLOAD_FOLDER_DOCKER_HOST:-./tmp}:/data/tmp"
      - "${YOUTUBE_COOKIES_FILE_PATH_DOCKER_HOST:-./cookies/youtube_cookies.txt}:/config/youtube_cookies.txt"
    restart: unless-stopped
